name: My First Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  schedule:
    - cron: '0 5 * * 1-5'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14, 16, 18]
        platform: [ubuntu-latest, macos-latest, windows-latest]
        exclude:
          - platform: macos-latest
            node-version: 14
      fail-fast: false

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: latest

    - name: Install dependencies
      run: npm ci

    - name: Build and Test
      run: npm run build && npm run test
      continue-on-error: true
      
    - name: Print a message
      run: echo "Hello, world!"